### ISSUE TITLE
async handler error: GUI - video_player possibly conflicting thread

### ISSUE THREAD

**Issue by mattsmith803** [SCCapstone/DJ-VJ#113]
* occasionally I get an "async handler deleted by the wrong thread" error
* based on my research into it, I'm thinking it's because once we load a show, the GUI and the video player are on the same thread and when python goes to garage collect the GUI, it accidentally closes the video_player

* a possible solution I've gathered from [here](https://stackoverflow.com/questions/27073762/tcl-asyncdelete-error-multithreading-python) is to `.quit()` the mainloop in the GUI
* or I could put the video_player on a new thread, but since we are no longer using the GUI at that point, to me it makes more sense to look into properly closing the GUI

* I've experimented with adding `gui.IntroScreen().quit()` to main.py after getting the show_params. It seems to help, but it does this weird thing where the splash screen splashes again and then the rest of the program runs
* perhaps adding deconstructors to each class of the GUI with this quit function could help?

**Comment by aholdeman** [comment]
I don't think this will affect the executable, so it should be okay as is.
