### ISSUE TITLE
Add volume option to GUI

### ISSUE THREAD

**Issue by mattsmith803** [SCCapstone/DJ-VJ#156]
We have the ability to measure volume in the backend. Could add this option to the GUI for users to use. 

After #155 gets merged, the program measures in dB (decibels), which isn't the most user friendly measurement so might need to come up with usability solution like a slider or give 'soft', 'medium', 'loud' options.

**Comment by aholdeman** [comment]
Okay so at this point, I can add the volume option but it's probably going to have to stay in dB. Should I go ahead and add it, or scrap it for usability sake?

**Comment by mattsmith803** [comment]
I think scrap it. So many variables would come into effect when using it. Each performer will perform a piece different, each room will sound different, the microphone sensitivity will drastically vary from microphone to microphone. All of our other features would be pretty consistent no matter these variables.
