### ISSUE TITLE
Doesnt free up terminal

### ISSUE THREAD

**Issue by jmeisten** [SCCapstone/DJ-VJ#176]
On linux when the user leaves the app, it does not seem to release control of the terminal. Appears to create a secondary window named "window:" that hides in the bottom corner of the screen
![Capture](https://user-images.githubusercontent.com/42556598/56102164-02e5e800-5ef9-11e9-887b-cc9be7f1e3e4.PNG)

**Comment by aholdeman** [comment]
I think this issue was fixed by the #172 PR. @mattsmith803 @TMike1996 Does that sound right?

**Comment by mattsmith803** [comment]
If "close application from menu" means pressing the "X" button from the home screen that we created then yes. 

If "terminate program / close application from menu" means pressing the x button on a system window bar (like where close, minimize, full screen buttons are on a mac), then that's different.

**Comment by mattsmith803** [comment]
I don't believe our program uses the system windows, but Linux might force the app to be in a system window.

**Comment by jmeisten** [comment]
Yes the button on the GUI on Linux causes this. I am the only one to do this from my group due to the others not being able to set this up. I was only get this to work in Linux not my windows machine. I would recommend creating an in depth installation guide for all windows because this could be endemic to Linux or could be a wider problem

**Comment by aholdeman** [comment]
Closed by #172
