### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by jmeisten** [SCCapstone/DJ-VJ#177]
Threading test

![thread](https://user-images.githubusercontent.com/42556598/56102215-a505d000-5ef9-11e9-9e98-e4d9587d61b8.PNG)

Test Averages
![avg](https://user-images.githubusercontent.com/42556598/56102214-a2a37600-5ef9-11e9-9201-098f44c0dc80.PNG)

**Comment by mattsmith803** [comment]
Closed by #199
