### ISSUE TITLE
add chord analysis feature

### ISSUE THREAD

**Issue by mattsmith803** [SCCapstone/DJ-VJ#75]
add the ability to analyze the chord of a given sample.

#### research
* [C++ open source package](https://github.com/adamstark/Chord-Detector-and-Chromagram) for chord analysis
* [cython](http://docs.cython.org/en/latest/) for interfacing python and C++ code

**Comment by aholdeman** [comment]
Pour one out for chord analysis #RIP #WeWillAlwaysRemember
